package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-05-03T10:26:30.680+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IWSLim5AP")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IWSLim5AP {

    @WebMethod(operationName = "LoadIMG1", action = "urn:WSLim5APIntf-IWSLim5AP#LoadIMG1")
    public void loadIMG1(
        @WebParam(partName = "xctxt", name = "xctxt")
        java.lang.String xctxt,
        @WebParam(partName = "xretxt", mode = WebParam.Mode.OUT, name = "xretxt")
        javax.xml.ws.Holder<java.lang.String> xretxt,
        @WebParam(partName = "xrpic1", mode = WebParam.Mode.OUT, name = "xrpic1")
        javax.xml.ws.Holder<byte[]> xrpic1,
        @WebParam(partName = "xrpic2", mode = WebParam.Mode.OUT, name = "xrpic2")
        javax.xml.ws.Holder<byte[]> xrpic2,
        @WebParam(partName = "xrpic3", mode = WebParam.Mode.OUT, name = "xrpic3")
        javax.xml.ws.Holder<byte[]> xrpic3
    );

    @WebMethod(operationName = "RecIMG", action = "urn:WSLim5APIntf-IWSLim5AP#RecIMG")
    @WebResult(name = "xrtxt", targetNamespace = "http://tempuri.org/", partName = "xrtxt")
    public java.lang.String recIMG(
        @WebParam(partName = "xctxt", name = "xctxt")
        java.lang.String xctxt,
        @WebParam(partName = "xattach", name = "xattach")
        byte[] xattach
    );

    @WebMethod(action = "urn:WSLim5APIntf-IWSLim5AP#textrec")
    @WebResult(name = "return", targetNamespace = "http://tempuri.org/", partName = "return")
    public java.lang.String textrec(
        @WebParam(partName = "xcrec", name = "xcrec")
        java.lang.String xcrec
    );

    @WebMethod(action = "urn:WSLim5APIntf-IWSLim5AP#txtcompname")
    @WebResult(name = "return", targetNamespace = "http://tempuri.org/", partName = "return")
    public java.lang.String txtcompname();

    @WebMethod(operationName = "IMGsd", action = "urn:WSLim5APIntf-IWSLim5AP#IMGsd")
    @WebResult(name = "xrtxt", targetNamespace = "http://tempuri.org/", partName = "xrtxt")
    public java.lang.String imGsd(
        @WebParam(partName = "xctxt", name = "xctxt")
        java.lang.String xctxt,
        @WebParam(partName = "xattach", name = "xattach")
        byte[] xattach
    );
}
