package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-05-03T10:26:30.693+05:30
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "IWSLim5APservice",
                  wsdlLocation = "file:/D:/Sadath/Personal/REPO/soap-mime/src/main/resources/IWSLim5AP.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class IWSLim5APservice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "IWSLim5APservice");
    public final static QName IWSLim5APPort = new QName("http://tempuri.org/", "IWSLim5APPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Sadath/Personal/REPO/soap-mime/src/main/resources/IWSLim5AP.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IWSLim5APservice.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Sadath/Personal/REPO/soap-mime/src/main/resources/IWSLim5AP.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IWSLim5APservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IWSLim5APservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IWSLim5APservice() {
        super(WSDL_LOCATION, SERVICE);
    }

    public IWSLim5APservice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IWSLim5APservice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IWSLim5APservice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IWSLim5AP
     */
    @WebEndpoint(name = "IWSLim5APPort")
    public IWSLim5AP getIWSLim5APPort() {
        return super.getPort(IWSLim5APPort, IWSLim5AP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWSLim5AP
     */
    @WebEndpoint(name = "IWSLim5APPort")
    public IWSLim5AP getIWSLim5APPort(WebServiceFeature... features) {
        return super.getPort(IWSLim5APPort, IWSLim5AP.class, features);
    }

}
