
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tempuri;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-05-03T10:26:30.612+05:30
 * Generated source version: 3.2.4
 *
 */

@javax.jws.WebService(
                      serviceName = "IWSLim5APservice",
                      portName = "IWSLim5APPort",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "file:/D:/Sadath/Personal/REPO/soap-mime/src/main/resources/IWSLim5AP.wsdl",
                      endpointInterface = "org.tempuri.IWSLim5AP")

public class IWSLim5APPortImpl implements IWSLim5AP {

    private static final Logger LOG = Logger.getLogger(IWSLim5APPortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tempuri.IWSLim5AP#loadIMG1(java.lang.String xctxt, java.lang.String xretxt, byte[] xrpic1, byte[] xrpic2, byte[] xrpic3)*
     */
    public void loadIMG1(java.lang.String xctxt, javax.xml.ws.Holder<java.lang.String> xretxt, javax.xml.ws.Holder<byte[]> xrpic1, javax.xml.ws.Holder<byte[]> xrpic2, javax.xml.ws.Holder<byte[]> xrpic3) {
        LOG.info("Executing operation loadIMG1");
        System.out.println(xctxt);
        try {
            java.lang.String xretxtValue = "";
            xretxt.value = xretxtValue;
            byte[] xrpic1Value = new byte[0];
            xrpic1.value = xrpic1Value;
            byte[] xrpic2Value = new byte[0];
            xrpic2.value = xrpic2Value;
            byte[] xrpic3Value = new byte[0];
            xrpic3.value = xrpic3Value;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IWSLim5AP#recIMG(java.lang.String xctxt, byte[] xattach)*
     */
    public java.lang.String recIMG(java.lang.String xctxt, byte[] xattach) {
        LOG.info("Executing operation recIMG");
        System.out.println(xctxt);
        System.out.println(xattach);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IWSLim5AP#textrec(java.lang.String xcrec)*
     */
    public java.lang.String textrec(java.lang.String xcrec) {
        LOG.info("Executing operation textrec");
        System.out.println(xcrec);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IWSLim5AP#txtcompname()*
     */
    public java.lang.String txtcompname() {
        LOG.info("Executing operation txtcompname");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IWSLim5AP#imGsd(java.lang.String xctxt, byte[] xattach)*
     */
    public java.lang.String imGsd(java.lang.String xctxt, byte[] xattach) {
        LOG.info("Executing operation imGsd");
        System.out.println(xctxt);
        System.out.println(xattach);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
